const BANCOS_MEXICO = [
  "BBVA",
  "Banamex / Citibanamex",
  "Santander",
  "Banorte",
  "HSBC",
  "Scotiabank",
  "Inbursa",
  "American Express",
  "Banco Azteca",
  "Mifel",
  "Invex",
  "Nu",
  "Mercado Pago",
  "Banregio",
  "Afirme",
  "Banco del Bajío (BanBajío)",
  "Banjercito",
  "Bancoppel",
  "Compartamos Banco",
  "Banco Famsa",
  "Multiva",
  "Ve por Más (BX+)",
  "CIBanco",
  "Hey Banco",
  "Klar",
  "Stori",
  "Rappi (RappiCard)",
  "Otro",
];

window.BANCOS_MEXICO = BANCOS_MEXICO;
